#file: noinspection SpringBootApplicationYaml
# 特定的文本描述文件，一般会出现在软件项目的配置上
# 可以使用application.properties实现相同的功能
source:
  mysql: mysql://localhost:3306/gardenia
  redis: redis://localhost:6379/gardenia
  messages: 沐言科技：www.yootk.com,李兴华的高薪就业编程训练营：www.edu.yootk.com   # 测试list注入
  # noinspection SpringBootApplicationYaml
  infos: "{'gardenia': 'www.gardenia.com', 'teacher': '李兴华'}"    # 使用SpEL表达式描述的map集合

# 以下是映射成配置文件的配置
muyan:
  mysql: mysql://localhost:3306/gardenia
  redis: redis://localhost:6379/gardenia
  messages: # 在spring中list和数组几乎是对等的关系
    - 沐言科技：www.yootk.com
    - 李兴华的高薪就业编程训练营：www.edu.yootk.com
  books: # 按map进行的配置
    javaBase: 《java面向对象就业编程实战》
    javaApplication: 《java应用技术就业编程实战》
    javaWeb: 《javaWeb就业编程实战》
    springBoot: 《SpringBoot就业编程实战》
    springCloud: 《SpringCloud就业编程实战》
object:   # com.gardenia.web.vo.Dept类的映射
  dept_no: 10
  d_name: 教学研发部
  company:    # 关联其他类的引用
    cid: 1009
    name: 沐言科技
  # 以list方式注入
  emps:
    - emp_no: 7369
      emp_name: Smith
      job: 办事员
    - emp_no: 7366
      emp_name: Allen
      job: 部门经理
    - emp_no: 7839
      emp_name: King
      job: 董事长
  # 以数组方式注入
  empList[0]:
    emp_no: 7369
    emp_name: Smith
    job: 办事员
  empList[1]:
    emp_no: 7366
    emp_name: Allen
    job: 部门经理
  empList[2]:
    emp_no: 7839
    emp_name: King
    job: 董事长
server:
  port: 80
  servlet:
    # 虚拟访问路径
    context-path: /muyan
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        # 开放全部的监控接口
        include: "*"
      # 默认值: /actuator
      base-path: /actuator
  endpoint:
    # 开启远程关闭功能
    shutdown:
      enabled: true
    # 健康检查，添加下面两项，日志中才会显示详细的健康检测信息
    health:
      # 显示异常信息
      show-details: always
      # 显示组件信息
      show-components: always
# 不知道为啥，info信息没有出来
info:
  apps: 1111
# Spring简单日志配置
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} [%thread] %clr(-%5p) %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: /mnt/logs/gardenia
  level:
    root: info
    com.gardenia.web.action.LogAction: trace

