# 导入环境变量 http-client.private.env.json:dynamic-aop
### 待测试方法
GET http://localhost:8080/aop/dynamic/fun
Accept: application/json

### 通过表达式增加
GET http://localhost:8080/aop/dynamic/add?interceptorClass={{interceptorOne}}&expression={{expression}}}
Accept: application/json

### 通过表达式删除
GET http://localhost:8080/aop/dynamic/del?interceptorClass={{interceptorOne}}&expression={{expression}}
Accept: application/json

### 通过注解添加
GET http://localhost:8080/aop/dynamic/add?interceptorClass={{interceptorTwo}}&annotationClass={{annotationClass}}
Accept: application/json

### 通过注解删除
GET http://localhost:8080/aop/dynamic/del?interceptorClass={{interceptorTwo}}&annotationClass={{annotationClass}}
Accept: application/json